language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.05 PINS="bin_prot.113.33.00+4.05:https://github.com/talex5/bin_prot.git#113.33.00+4.05 irmin.0.12.0:https://github.com/talex5/irmin.git#v0.12.0-cuekeeper git.1.9.3:https://github.com/talex5/ocaml-git.git#irmin-0.11"
